### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by strawberry-kitten** [OrnitheMC/ornithe-template-mod#3]
On Intellij IDEA Community 2024.3

A problem occurred configuring project ':client'.
> Could not resolve all dependencies for configuration ':client:exceptions'.
   > Could not find net.ornithemc:raven:b1.8.1-client+build.1.
     Searched in the following locations:
       - file:/home/username/Desktop/minecraft/ornithe-template-mod-quilt-split/.gradle/quilt-loom-cache/remapped_mods/net/ornithemc/raven/b1.8.1-client+build.1/raven-b1.8.1-client+build.1.pom
       - file:/home/username/.gradle/caches/quilt-loom/minecraftMaven/net/ornithemc/raven/b1.8.1-client+build.1/raven-b1.8.1-client+build.1.pom
       - file:/home/username/Desktop/minecraft/ornithe-template-mod-quilt-split/.gradle/quilt-loom-cache/minecraftMaven/net/ornithemc/raven/b1.8.1-client+build.1/raven-b1.8.1-client+build.1.pom
       - https://maven.fabricmc.net/net/ornithemc/raven/b1.8.1-client+build.1/raven-b1.8.1-client+build.1.pom
       - https://maven.quiltmc.org/repository/release/net/ornithemc/raven/b1.8.1-client+build.1/raven-b1.8.1-client+build.1.pom
       - https://libraries.minecraft.net/net/ornithemc/raven/b1.8.1-client+build.1/raven-b1.8.1-client+build.1.jar
       - https://repo.maven.apache.org/maven2/net/ornithemc/raven/b1.8.1-client+build.1/raven-b1.8.1-client+build.1.jar
       - https://repo.maven.apache.org/maven2/net/ornithemc/raven/b1.8.1-client+build.1/raven-b1.8.1-client+build.1.pom
       - https://maven.ornithemc.net/releases/net/ornithemc/raven/b1.8.1-client+build.1/raven-b1.8.1-client+build.1.pom
       - https://maven.minecraftforge.net/net/ornithemc/raven/b1.8.1-client+build.1/raven-b1.8.1-client+build.1.pom
       - https://maven.minecraftforge.net/net/ornithemc/raven/b1.8.1-client+build.1/raven-b1.8.1-client+build.1.jar

**Comment by SpaceWalkerRS** [comment]
Raven and Sparrow are not yet out for b1.8.1, so remove those dependencies in the build script.
